### ISSUE TITLE
Diseño de TexBox personalizado con Visual Studio

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Valentiin01#2]
[Diseño TexBox_Genaro Santiago Valentin.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Valentiin01/files/6770622/Diseno.TexBox_Genaro.Santiago.Valentin.pdf)

**Comment by MLR062998** [comment]
calificacion: 20%

**Comment by josealfredo79** [comment]
La calificación no puede ser la máxima, se entrego al final de semestre
